Fix issue #11328
libsdl-org/SDL pull request #11361
Opened 2024-10-28 22:45 UTC by Dv-Senna

## Description
Add the lines
```cpp
#undef VK_DEFINE_HANDLER
#undef VK_DEFINE_NON_DISPATCHABLE_HANDLE
```
At the end of `SDL_vulkan.h` to allow `vulkan/vulkan.h` to define `VK_NULL_HANDLE` (and certainly other stuff as well) properly for C++ and `vulkan/vulkan.hpp`.

This change was tested using https://github.com/feelamee/sdl-bug-with-vulkan-cpp-api (for checking compilation errors) and SDL's testvulkan on x86-64 archlinux, and compiled with gcc.

## Existing Issue(s)
Fix to issue #11328

2024-10-28 23:02 UTC, sezero commented
This seems OK to me, and, if accepted, should be cherry-picked to SDL2 too.

2024-10-29 15:23 UTC, slouken requested changes
This should probably be moved inside the relevant block, around line 70.

2024-10-29 16:30 UTC, icculus commented
As a totally pedantic thing, it would be nice if this had an actual description of the problem in the commit message instead of "fix issue X" so we can read this in the commit log without going through GitHub.

The description in the pull request itself is very good, that could be used in the commit message.

2024-10-29 16:50 UTC, Dv-Senna commented
I moved the undefs just after their last use and I put a more descriptive commit message as requested.

2024-10-29 17:30 UTC, merged

2024-10-29 17:36 UTC, sezero commented
Merged by squashing and tweaked the commit message, and cherry picked to SDL2 branch as https://github.com/libsdl-org/SDL/commit/478dff35859a1851abf869aa873c7ca8442acdea

I don't know the reason for clang-cl x86 failure in CI: https://github.com/libsdl-org/SDL/actions/runs/11578625405/job/32234501685?pr=11361