[WIP] Add SDL_GetAudioDeviceSpec
libsdl-org/SDL pull request #4109
Opened 2021-02-18 21:23 UTC by flibitijibibo

This is a Git version of the patch found in #2911.

At the moment this only works with PulseAudio. This would be pretty easy to add to the Pipewire backend as well. The rest... there are a couple backends that make it easy to query, while others require initializing the device first. This at least sets things up in the common code, though we could use some more implementations to make sure this makes any sense at all.

2021-02-18 21:52 UTC, sezero commented
Changes to dynapi side are wrong: New additions must b e appended, not inserted.
Reverting only the dynapi changes and running gendynapi.pl should do the trick.

2021-02-18 21:57 UTC, flibitijibibo commented
Pushed the updated dynapi files.

2021-02-20 19:40 UTC, icculus requested changes

2021-02-20 19:40 UTC, icculus commented on src/audio/SDL_audio.c
> +    }
```c
return SDL_InvalidParamError("spec");
```

2021-02-20 19:40 UTC, icculus commented on src/audio/SDL_audio.c
> +        SDL_zerop(spec);
Just zerop(spec) after we know it's not NULL, so we don't have to do this on each error condition (and risk forgetting one later).

2021-02-20 19:40 UTC, icculus commented on include/SDL_audio.h
> +
Should this not return an int so we report errors?

2021-02-20 19:40 UTC, icculus commented on src/audio/pulseaudio/SDL_pulseaudio.c
> +            SDL_AddAudioDevice(SDL_TRUE, i->description, &spec, (void *) ((size_t) i->index+1));
Can we move this to a common function instead of copy/pasting it between SourceInfoCallback and SinkInfoCallback?

2021-02-20 19:41 UTC, icculus commented on src/audio/pulseaudio/SDL_pulseaudio.c
> +            SDL_AddAudioDevice(SDL_TRUE, i->description, &spec, (void *) ((size_t) i->index+1));
(The switch statement, I mean, which I failed to highlight properly.)

2021-02-20 22:52 UTC, flibitijibibo commented
Updated with suggested changes.

2021-02-24 21:36 UTC, flibitijibibo commented
Pushed an update with a sloppy, totally untested attempt at getting WASAPI Win32 device information. I wasn't able to find anything for WinRT, but it seems like the same information would be in the monolithic Dictionary<string, string> found in DeviceInformation.

2021-02-27 19:31 UTC, flibitijibibo commented
Another untested platform, this time it's WinRT - the DeviceInformation is even more undocumented than the Win32 equivalent, so my only assumption that this will work is the fact that XBMC passes the PKEY as a string to the CreateWatcher API and it appears to work for them. Also, somehow they made Vectors platform-specific.

The last API that we care about from FNA's perspective is CoreAudio, which I know the least about. The rest of the APIs listed in the TODO are totally foreign to me, so someone else will have to check those out.

2021-02-27 22:34 UTC, flibitijibibo commented
Scribbled in CoreAudio and tested Win32/WinRT, all of the backends I'm able to work on have been completed and are verified as working.

2021-03-01 03:47 UTC, flibitijibibo commented
@Kontrabant Now that the Pipewire support is in, do you still have that patch for GetAudioDeviceSpec? I can apply it to this branch right away.

2021-03-01 05:13 UTC, Kontrabant requested changes
The audio spec struct is already there and filled in, just need to pass it to the SDL_AddAudioDevice() function.

2021-03-01 05:13 UTC, Kontrabant commented on src/audio/pipewire/SDL_pipewire.c
> +        SDL_AddAudioDevice(node->is_capture, node->name, NULL, PW_ID_TO_HANDLE(node->id));
```suggestion
        SDL_AddAudioDevice(node->is_capture, node->name, &node->spec, PW_ID_TO_HANDLE(node->id));
```

2021-03-01 05:13 UTC, Kontrabant commented on src/audio/pipewire/SDL_pipewire.c
> +        SDL_AddAudioDevice(io->is_capture, io->name, NULL, PW_ID_TO_HANDLE(io->id));
```suggestion
        SDL_AddAudioDevice(io->is_capture, io->name, &io->spec, PW_ID_TO_HANDLE(io->id));
```

2021-03-01 14:09 UTC, flibitijibibo commented
Perfect, thanks! This is ready to go once more.

2021-03-03 03:14 UTC, flibitijibibo commented
Pushed one more change, to try and finalize alsa/directsound/winmm. To the best of my knowledge, all three require opening the device to get any information, which in my opinion means it's inaccessible for the purposes of this API. In way this makes sense - all the implementations that _do_ support it are either sound servers or sound APIs operating in a "shared" mode, where the mix format would be known at the time you query device information. The ones that _don't_ were designed to take you directly to the sound driver, where you're expected to get the information at the same time that you open the device connection. This API wants to get info _before_ we open the connection, so with that in mind I've documented the three APIs to note why it's not possible to implement (though WinMM inexplicably notes channel count, so that's cool I guess?).

OS/2, QSA, and generic Unix are _really_ out of my way though, so those will remain untouched until whoever maintains those platforms can check it out. For now, this patch covers every platform that's advertised as officially supported _and_ supports device hotplugging.

2021-03-05 07:01 UTC, Cacodemon345 commented
The QSA backend, like ALSA, can only determine the information at opening time. Same seems to go for the Solaris and NetBSD backend which you apparently forgot.

2021-03-05 18:34 UTC, flibitijibibo commented
Pushed to note the NULL spec for QSA and EnumUnixAudioDevices. OS/2 is the only backend left that is marked as TODO, but I'm going to guess that it's also unsupported there.

2021-03-05 18:42 UTC, sezero commented
> OS/2 is the only backend left that is marked as TODO, but I'm going to guess that it's also unsupported there.

Not supported as far as I know

2021-03-05 18:45 UTC, flibitijibibo commented
A quick look at the structs used by the implementation seems to agree - pushed one more time to remove the TODO. All drivers using SDL_AddAudioDevice have now been accounted for.

2021-03-05 20:03 UTC, merged