wayland: Fix toggling fullscreen with fixed-size windows
libsdl-org/SDL pull request #4285
Opened 2021-04-06 22:14 UTC by flibitijibibo

Fixes #4281.

Continuing off my work from #4065, it looks like Wayland took even _more_ notes from X and made the min/max an issue when calling the set_fullscreen functions, causing the display server to clamp the window and resize it to something really weird and wrong. The solution was to fold _all_ of the min/max work into a new function and do a full commit every single time we change the dimensions in some way. It turns out it's cleaner like this anyway!

2021-04-06 22:29 UTC, christianrauch requested changes

2021-04-06 22:29 UTC, christianrauch commented on src/video/wayland/SDL_waylandwindow.c
> +    const int maxsize = 0x7FFFFFFF;
If you want to tell the Wayland compositor/server not to constrain the maximum size, just send 0: `xdg_toplevel_set_max_size(..., 0, 0)`. There is no need to figure out the maximum size.

2021-04-06 22:29 UTC, christianrauch commented on src/video/wayland/SDL_waylandwindow.c
> +    WAYLAND_wl_display_flush(data->display);
The "flush" is not required. Only the "commit" is required to tell the compositor that you are done with setting a new state.

2021-04-06 22:37 UTC, flibitijibibo commented
Pushed an update per review comments from @christianrauch, thanks for the tips!

2021-04-07 20:49 UTC, flibitijibibo commented
Pushed an additional commit that fixes this for Plasma as well. The behavior was radically different because of an unassigned wl_output variable, which _should_ have affected every Wayland environment but mysteriously only affected Plasma.

2021-04-07 20:53 UTC, merged