wayland: restore floating states
libsdl-org/SDL pull request #4570
Opened 2021-08-01 17:42 UTC by christianrauch

Store and restore floating dimensions when restoring from maximised/fullscreen to floating state. This affects the xdg and libdecor implementations.

## Description
We now store the window size if the window is in a floating mode (not fullscreen/maxmised/tiled) so that when we have to restore from a  fullscreen/maxmised/tiled state to a floating state, we use our previous floating dimensions.

I added a dedicated "floating_*" set of variables and did not reuse the `windowed` that seem to have a similar use. This is because `windowed` is only used for fullscreen and is in a more global scope, whose changes might have some undesired effects. The new "floating" variables are only used within Wayland and should not affect the public SDL API.

There are remaining issues with transitioning from between non-floating states (e.g. floating -> maximised -> fullscreen -> maximised) which only work with libdecor, but not with the xdg baseline.

## Existing Issue(s)
Fixes #4562

2021-08-01 18:32 UTC, slouken requested changes

2021-08-01 18:32 UTC, slouken commented on src/video/wayland/SDL_waylandwindow.c
> +    bool floating = true;
This should be SDL_bool, as bool isn't available for C89 compilers.

2021-08-01 18:32 UTC, slouken commented on src/video/wayland/SDL_waylandwindow.c
> +    height = (height==0) ? window->h : height;
Style should be (width == 0), with spaces around "=="

2021-08-01 19:41 UTC, christianrauch commented
> FYI, the windowed variable holds the current window size, regardless of floating/maximized/tiled state, and the fullscreen_mode holds the state when the window is in fullscreen state.

Alright. Then it makes sense to have a dedicated variable within Wayland for this.

2021-08-01 19:55 UTC, flibitijibibo requested changes
Haven't tested yet so this is just cosmetic stuff.

CC @dos1, this likely affects #4563.

2021-08-01 19:55 UTC, flibitijibibo commented on src/video/wayland/SDL_waylandwindow.c
> +            floating = false;
These should be SDL_FALSE

2021-08-01 20:13 UTC, christianrauch commented on src/video/wayland/SDL_waylandwindow.c
> +            floating = false;
Ups, missed that. Fixed now.

2021-08-01 22:14 UTC, merged

2021-08-01 23:58 UTC, dos1 commented
> CC @dos1, this likely affects #4563.

Tried it and it does not fix the crashes - and looking at the code it doesn't seem like it could.

BTW. It introduces compilation warnings:

```
/home/dos/git/SDL/src/video/wayland/SDL_waylandwindow.c: In function ‘handle_configure_xdg_toplevel’:
/home/dos/git/SDL/src/video/wayland/SDL_waylandwindow.c:219:9: warning: enumeration value ‘XDG_TOPLEVEL_STATE_RESIZING’ not handled in switch [-Wswitch]
  219 |         switch (*state) {
      |         ^~~~~~
/home/dos/git/SDL/src/video/wayland/SDL_waylandwindow.c:219:9: warning: enumeration value ‘XDG_TOPLEVEL_STATE_ACTIVATED’ not handled in switch [-Wswitch]
/home/dos/git/SDL/src/video/wayland/SDL_waylandwindow.c: In function ‘decoration_frame_configure’:
/home/dos/git/SDL/src/video/wayland/SDL_waylandwindow.c:352:5: warning: enumeration value ‘LIBDECOR_WINDOW_STATE_NONE’ not handled in switch [-Wswitch]
  352 |     switch (window_state) {
      |     ^~~~~~
/home/dos/git/SDL/src/video/wayland/SDL_waylandwindow.c:352:5: warning: enumeration value ‘LIBDECOR_WINDOW_STATE_ACTIVE’ not handled in switch [-Wswitch]
/home/dos/git/SDL/src/video/wayland/SDL_waylandwindow.c:352:5: warning: enumeration value ‘LIBDECOR_WINDOW_STATE_TILED_LEFT’ not handled in switch [-Wswitch]
/home/dos/git/SDL/src/video/wayland/SDL_waylandwindow.c:352:5: warning: enumeration value ‘LIBDECOR_WINDOW_STATE_TILED_RIGHT’ not handled in switch [-Wswitch]
/home/dos/git/SDL/src/video/wayland/SDL_waylandwindow.c:352:5: warning: enumeration value ‘LIBDECOR_WINDOW_STATE_TILED_TOP’ not handled in switch [-Wswitch]
/home/dos/git/SDL/src/video/wayland/SDL_waylandwindow.c:352:5: warning: enumeration value ‘LIBDECOR_WINDOW_STATE_TILED_BOTTOM’ not handled in switch [-Wswitch]
```

2021-08-02 14:55 UTC, flibitijibibo commented
In addition to producing a bunch of warnings, it also does not actually work - it introduces a _massive_ performance regression and seems to just break decorations entirely - 31f0bb7 in particular needs to be reverted.

2021-08-02 16:10 UTC, flibitijibibo commented
One partial revert and one warning fix:

https://github.com/libsdl-org/SDL/commit/754aa2d321031afe1fd36f99f6ba45f53984d544
https://github.com/libsdl-org/SDL/commit/dab33844e386c4d5553eb49c578ccb0ee18bc947

The warning fix isn't too big of a deal, but the revert possibly is - I basically had to undo the new configure implementation, which means at this poing floating_width/floating_height aren't actually read anymore, just stored. There's probably a correct way to do this, but I did notice that in testing the latest revision I'm not fighting the fullscreen->windowed case that I was earlier, so this may be fine as-is? (Which would be a bummer, because I kind of wanted both paths to be basically the same code.)