Fix text_input_v3 preedit string
libsdl-org/SDL pull request #5280
Opened 2022-01-31 00:48 UTC by wengxt

## Description

For every batch of text_input_v3 updates, if there is no preedit in this
batch, preedit should be cleared.

## Existing Issue(s)

2022-01-31 04:04 UTC, flibitijibibo commented
Makes sense to me... out of curiosity what's a good way to test this, I had a lot of difficulty testing certain text input things because I have close to zero experience past ASCII input.

2022-01-31 04:13 UTC, wengxt commented
> Makes sense to me... out of curiosity what's a good way to test this, I had a lot of difficulty testing certain text input things because I have close to zero experience past ASCII input.

In KDE, it will just start an in process compositor, but kwin itself has more library to use... Weston doesn't have text input v3 support so there's no luck here. Not sure if using wlroots can be easier for SDL project.

2022-01-31 18:47 UTC, flibitijibibo requested changes
Looked at the other backends for reference and they pretty much do what this does, so with this one change we're good to go.

2022-01-31 18:47 UTC, flibitijibibo commented on src/video/wayland/SDL_waylandevents.c
> +        SDL_SendEditingText(buf, 0, 0);
Looked around the rest of the source, turns out other backends do it like this:

```suggestion
        SDL_SendEditingText("", 0, 0);
```

2022-02-01 20:50 UTC, flibitijibibo approved these changes
Perfect, thanks for checking this out!

2022-02-01 20:51 UTC, merged