[PSP] Remove legacy and unused Makefile.psp
libsdl-org/SDL pull request #5291
Opened 2022-02-01 21:46 UTC by fjtrujy

## Description
This PR basically removes the file `Makefile.psp` which is not being used/needed anymore.

Thanks

2022-02-01 21:49 UTC, slouken commented
This is still referenced by docs/README-psp.md

2022-02-01 22:03 UTC, ccawley2011 commented
In addition, `include/SDL_config_psp.h` (and the relevant lines in `SDL_config.h`) can be removed as well, since it's only used by `Makefile.psp`.

2022-02-02 07:19 UTC, fjtrujy commented
Done, thanks, guys!

Pinging @sharkwouter because I have added his name in the `readme-psp.md`

2022-02-02 08:04 UTC, sharkwouter commented
Oh thanks! I think this is a good idea. Maintaining both scripts has not really been working out.

2022-02-02 08:34 UTC, sharkwouter requested changes

2022-02-02 08:34 UTC, sharkwouter commented on docs/README-psp.md
> +cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$PSPDEV/psp/share/pspdev.cmake -DSDL_TEST=ON
I would not recommend people to use ``-DSDL_Test=ON`` here. If that is used, ``make install`` does not work unfortunately.

2022-02-02 09:26 UTC, sharkwouter approved these changes
Looks good now

2022-02-02 13:36 UTC, merged