bug fix add sync geometry to xdg_surface
libsdl-org/SDL pull request #6760
Opened 2022-12-05 02:45 UTC by Hleia

When connecting multiple screens with different

resolutions,create windows on each screen, and

we need synchronize the current window size to

xdg_surface geometry,otherwise xdg_surface geometry

will use the default。

Signed-off-by: Lei.Huang <leihuang@amd.com>

## Description

[why]
When connecting multiple screens with different resolutions, create windows on each screen, and we need synchronize the current window size to xdg_surface geometry。
otherwise xdg_surface geometry  will use the default。
As a result, three screens are connected, one with 4k resolution, two with 1080p resolution, and two with 1080p resolution are distributed to the androd vm. The following errors will occur when xen starts.
xdg_wm_base@19: error 4: xdg_surface geometry (3840 x 2160) is larger than the configured fullscreen state (1920 x 1080)。
[how]
Add synchronize the current window size to xdg_surface geometry.
## Existing Issue(s)

2022-12-05 17:07 UTC, flibitijibibo commented
Quick CC to @Kontrabant - I think we only removed that since we didn't think it was necessary, not sure if bringing it back would cause any issues. If not, let's definitely bring this back.

2022-12-05 18:00 UTC, Kontrabant requested changes
The original bug that needed this seemed to be fixed without it, but if it's still needed in certain scenarios, then we should absolutely put it back.  libdecor calls this itself with the dimensions of the content surface, so it should just be needed in the xdg_surface path.

It does need to be changed, though:

2022-12-05 20:39 UTC, Kontrabant commented
See #6768

2022-12-05 20:52 UTC, flibitijibibo commented
@Hleia, if #6768 fixes the issue for you I'll go ahead and merge that one in!

2022-12-13 05:46 UTC, flibitijibibo commented
This ended up being resolved by #6768, let us know if this is not actually the case!

2022-12-13 05:46 UTC, closed without merging