Check OpenGL errors before checking `glFramebufferTexture2DEXT()`
libsdl-org/SDL pull request #7938
Opened 2023-07-06 14:55 UTC by t-sin

This PR implements error check codes of `SDL_SetRenderTarget` OpenGL version marked as TODO.

It may be necessary to discuss some error message on some additional errors described below.

## Description

I meets an error caused by this TODO:

https://github.com/libsdl-org/SDL/blob/17e95345e39b2b3ce436ce3029175055c3d48869/src/render/opengl/SDL_render_gl.c#L887-L888

This error caused in a software using SDL2 via FFI (cf. issue is this https://github.com/lem-project/lem/issues/690 but this software is written in Common Lisp and I cannot write reproduce codes in C, sorry :sob:). After debugging this error  including compilation SLD2 on my machine, I found there is no error occur in this case.

Framebuffer-related errors can be checked with `glCheckFramebufferStatus()` function in a OpenGL extension, but framebuffer-related operations may occur some additionally errors not like `GL_FRAMEBUFFER_xxx` things. According to the Khronos group's document ([`glCheckFramebufferStatus()`](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glCheckFramebufferStatus.xhtml)), these errors may occur additionally: `GL_INVALID_ENUM` or `GL_INVALID_OPERATION`. They can be checked via OpenGL's `glGetError()` function and `glCheckFramebufferStatus()` returns zero, **NOT THE `GL_FRAMEBUFFER_COMPLETE`**, in these additionally cases.

So correct error handling on this TODO is:

1. Check the `glCheckFramebufferStatus()` for framebuffer-related errors
2. Check the `glGetError()` for additionally errors, if non-`GL_FRAMEBUFFER_COMPLETE` status in step 1
3. Raise an error if that additionally error occured

This PR implements this correct handling.

## Existing Issue(s)

I cannot find related issues.

2023-07-06 15:42 UTC, slouken commented
What is the status, if  status != GL_FRAMEBUFFER_COMPLETE_EXT and data->glGetError() == GL_NO_ERROR? You've changed the function so it would no longer return an error in this case.

2023-07-06 16:15 UTC, t-sin commented
> What is the status, if status != GL_FRAMEBUFFER_COMPLETE_EXT and data->glGetError() == GL_NO_ERROR? 

Your comment is so nice. The status is one of `GL_FRAMEBUFFER_xxx` things described that docs in this case but my PR has no these cases. I'll add some codes to catch these.

2023-07-06 16:17 UTC, icculus requested changes

2023-07-06 16:17 UTC, icculus commented on src/render/opengl/SDL_render_gl.c
> +                return SDL_SetError("glFramebufferTexture2DEXT() failed because of GL_INVALID_EMUM");
`GL_INVALID_EMUM` is a typo

2023-07-06 16:17 UTC, icculus commented on src/render/opengl/SDL_render_gl.c
> +            return SDL_SetError("glFramebufferTexture2DEXT() failed with (err, status) = (%d, %d)", err, status);
This `return` needs to be outside the `if`, or the function will report success if we have an incomplete framebuffer but glGetError() returns GL_NO_ERROR.

2023-07-29 02:42 UTC, t-sin commented
I fixed about those comments and now it checks all errors. Its compilation succeeded in my environment.

2023-08-07 14:55 UTC, t-sin commented
Ping! How about like this?

2023-08-08 18:46 UTC, icculus requested changes

2023-08-08 18:46 UTC, icculus commented on src/render/opengl/SDL_render_gl.c
> +            /* never reach here */
You can reach here, if glErr returns something other than GL_INVALID_ENUM or GL_INVALID_OPERATION. Even if the specs say it only returns those two errors, OpenGL implementations may get it wrong, or a later extension can add new errors.

2023-08-08 18:46 UTC, icculus commented on src/render/opengl/SDL_render_gl.c
> +            /* check additoinal errors */
"additional" is spelled wrong

2023-08-08 18:46 UTC, icculus commented on src/render/opengl/SDL_render_gl.c
> +            return 0;
This is still returning success when we get an incomplete framebuffer. I think there was a misunderstanding about our previous comments, where the flow of logic could accidentally fail to return an error in this case, now it's checking for that case explicitly and not returning an error.

2024-06-30 18:04 UTC, t-sin commented
I'm sorry for this very delay. I understood that comment below

> I think there was a misunderstanding about our previous comments,

and the reason of creating this issue is also incorrect testing.

So I closed this PR.

2024-06-30 18:04 UTC, closed without merging