Cleanup SDL scancode list
libsdl-org/SDL pull request #8596
Opened 2023-11-21 16:00 UTC by DJm00n

Remove duplicates:
- SDL_SCANCODE_APP1. Change references to the SDL_SCANCODE_COMPUTER;
- SDL_SCANCODE_APP2. Change references to the SDL_SCANCODE_CALCULATOR;
- SDL_SCANCODE_AUDIOMUTE. Change references to the SDL_SCANCODE_MUTE;

2023-11-28 21:57 UTC, slouken commented
This proposal is related:
https://github.com/libsdl-org/SDL/issues/6390

2023-11-29 10:59 UTC, DJm00n commented
Rebased.
@slouken please take a look

2023-11-29 15:36 UTC, slouken commented on include/SDL3/SDL_keycode.h
> -    SDLK_APP1 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_APP1),
Since these changes affect the public API, a note is needed in README-migration.md

2023-11-29 16:39 UTC, DJm00n commented on src/events/scancodes_linux.h
> +    /* 148, 0x094 */    SDL_SCANCODE_UNKNOWN,           /* KEY_PROG1 */
`KEY_PROG1` is mapped to HID `0x00010086 System App Menu` in Linux:
https://github.com/torvalds/linux/blob/18d46e76d7c2eedd8577fae67e3f1d4db25018b0/drivers/hid/hid-input.c#L819

`KEY_PROG1` doesn't have any standard HID mapping (but do have some vendor-specific):
https://github.com/search?q=repo%3Atorvalds%2Flinux+KEY_PROG2+path%3A%2F%5Edrivers%5C%2Fhid%5C%2F%2F&type=code

2023-12-21 03:47 UTC, slouken commented on src/events/scancodes_linux.h
> +    /* 148, 0x094 */    SDL_SCANCODE_UNKNOWN,           /* KEY_PROG1 */
Honestly, there probably isn't one for those scancodes specifically. People tend to like having lots of buttons available for game actions, but whether it's APP1 or COMPUTER it doesn't really matter.

2023-12-21 03:49 UTC, slouken requested changes
Please take a look at the unresolved comments above.

2024-03-23 23:41 UTC, slouken commented
Ping?

2024-08-06 16:36 UTC, slouken commented
This hasn't been updated in a while and we're cleaning house for SDL 3.0. Please feel free to reopen this if you'd like to clean it up and get it in!

2024-08-06 16:36 UTC, closed without merging